version: '3.5'

services:
  db_task_manager:
    container_name: db_task_manager
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=brokkko
      - POSTGRES_USER=brokkko
    image: postgres:14.5