spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: brokkko
    password: brokkko

  jpa:
    hibernate:
      ddl-auto: update

#  flyway:
#    baselineOnMigrate: true
#    locations: classpath:db/migration
#    schemas: public
#    enabled: true
#    fail-on-missing-locations: true